In [1]:
%reset -f
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("Ads_CTR_Optimisation.csv")
print(df.shape)
df.head(15)

(10000, 10)

    Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0      1     0     0     0     1     0     0     0     1      0
1      0     0     0     0     0     0     0     0     1      0
2      0     0     0     0     0     0     0     0     0      0
3      0     1     0     0     0     0     0     1     0      0
4      0     0     0     0     0     0     0     0     0      0
5      1     1     0     0     0     0     0     0     0      0
6      0     0     0     1     0     0     0     0     0      0
7      1     1     0     0     1     0     0     0     0      0
8      0     0     0     0     0     0     0     0     0      0
9      0     0     1     0     0     0     0     0     0      0
10     0     0     0     0     0     0     0     0     0      0
11     0     0     0     0     0     0     0     0     0      0
12     0     0     0     1     0     0     0     0     0      0
13     0     0     0     0     0     0     0     0     1      0
14     0     0     0     0     0     0     0     1     0      0

In [24]:
d = 10

number_of_selections = [0] * d  # each index is for individual ad, up to round n
sum_of_rewards = [0] * d        # each add will have as assosiated reward also..

# =============================================
add_selected = []
total_reward = 0
# =============================================
for n in range(2):
    ad = 0
    max_upper_bound = 0
    for i in range(10):
        if( number_of_selections[i] > 0 ):
            print("here need to be adjusted")
        else:
            upper_bound = 400000000
            print(f"{i} => {upper_bound}")
        if (upper_bound > max_upper_bound):
            max_upper_bound = upper_bound
            ad = i
            print(ad)
    # ------------------------------------------------------------------------------------
    # Before getting this level... keep in mind, it had already iterate 10 times of (i-loop)
    # ------------------------------------------------------------------------------------
    add_selected.append(ad)
    print(ad)
    number_of_selections[ad] = number_of_selections[ad] + 1
    reward = df.values[n, ad]
    sum_of_rewards[ad] = sum_of_rewards[ad] + reward
    total_reward = total_reward + reward
    
#     print(f"add_selected :-> {add_selected}")
#     print(f"Number of Se :-> {number_of_selections}")
#     print(f"add_selected :-> {add_selected}")
    print("==========================")

0 => 400000000
0
1 => 400000000
2 => 400000000
3 => 400000000
4 => 400000000
5 => 400000000
6 => 400000000
7 => 400000000
8 => 400000000
9 => 400000000
0
==========================
here need to be adjusted
0
1 => 400000000
2 => 400000000
3 => 400000000
4 => 400000000
5 => 400000000
6 => 400000000
7 => 400000000
8 => 400000000
9 => 400000000
0
==========================

In [40]:
import math
d = 10

number_of_selections = [0] * d  # each index is for individual ad, up to round n
sum_of_rewards = [0] * d        # each add will have as assosiated reward also..

# =============================================
upper_bound_record = []
add_selected = []
total_reward = 0
# =============================================
for n in range(11):
    ad = 0
    max_upper_bound = 0
    for i in range(10):
        if( number_of_selections[i] > 0 ):
            avg_reward = sum_of_rewards[i]/number_of_selections[i]
            delta_i = math.sqrt(3/2 * math.log(n + 1) / number_of_selections[i])
            upper_bound = avg_reward + delta_i
            upper_bound_record.append(upper_bound)
        else:
            upper_bound = 400000000
#             print(f"{i} => {upper_bound}")
        if (upper_bound > max_upper_bound):
            max_upper_bound = upper_bound
            ad = i
    # ------------------------------------------------------------------------------------
    # Before getting this level... keep in mind, it had already iterate 10 times of (i-loop)
    # ------------------------------------------------------------------------------------
    add_selected.append(ad)
    print(ad)
    number_of_selections[ad] = number_of_selections[ad] + 1
    reward = df.values[n, ad]
    sum_of_rewards[ad] = sum_of_rewards[ad] + reward
    total_reward = total_reward + reward
    
    print(f"{upper_bound}")
    print(f"add_selected :-> {add_selected}")
    print(f"Number of Se :-> {number_of_selections}")
    print("==========================")

0
400000000
add_selected :-> [0]
Number of Se :-> [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
==========================
1
400000000
add_selected :-> [0, 1]
Number of Se :-> [1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
==========================
2
400000000
add_selected :-> [0, 1, 2]
Number of Se :-> [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]
==========================
3
400000000
add_selected :-> [0, 1, 2, 3]
Number of Se :-> [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
==========================
4
400000000
add_selected :-> [0, 1, 2, 3, 4]
Number of Se :-> [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
==========================
5
400000000
add_selected :-> [0, 1, 2, 3, 4, 5]
Number of Se :-> [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
==========================
6
400000000
add_selected :-> [0, 1, 2, 3, 4, 5, 6]
Number of Se :-> [1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
==========================
7
400000000
add_selected :-> [0, 1, 2, 3, 4, 5, 6, 7]
Number of Se :-> [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
==========================
8
400000000
add_selected :-> [0, 1, 2, 3, 4, 5, 6, 7, 8]
Number of Se :-> [1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
==========================
9
400000000
add_selected :-> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Number of Se :-> [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
==========================
0
1.8965344471423544
add_selected :-> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
Number of Se :-> [2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
==========================

In [42]:
# upper_bound_record